{% set name = "latexmk" %}
{% set major = "4" %}
{% set minor = "85" %}
{% set version = major + "." + minor %}
{% set sha256 = "66c53f50f74fa3d7c651a3e9166856706b6196d58da1f4167630183a4abdc325" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://www.cantab.net/users/johncollins/latexmk/latexmk-{{ major }}{{ minor }}.zip
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  run:
    - perl

test:
  commands:
    - latexmk -h                # [not win]
    - perl -S latexmk.pl -h     # [win]

about:
  home: http://personal.psu.edu/jcc8//software/latexmk-jcc/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'A perl script for running LaTeX the correct number of times'
  description: |
    Latexmk is a perl script for running LaTeX the correct number of times to
    resolve cross references, etc; it also runs auxiliary programs (bibtex,
    makeindex if necessary, and dvips and/or a previewer as requested).
    It has a number of other useful capabilities, for example to start
    a previewer and then run latex whenever the source files are updated,
    so that the previewer gives an up-to-date view of the document.

extra:
  recipe-maintainers:
    - scopatz
    - xileF1337
