travis:
  secure:
    BINSTAR_TOKEN: EZPnpGC82TlvhAY1W/MReIuF1NeFQwNDRQtyPju7vwcGljyBabMAcG/5wvuRELVr8htuZNuM+ll/NuNw0PcE3ONnigErdNVktvaAhUTDi9FTRYKCBiFn7P4rOLvaiW7IQCnx7H+9YbcXHYl6wST3UIRbukSfBhAkHmMNw6KKGuMjLAvI/Mov7EvHRmzrSwWYjeyf3U+lo4loiVDVb8VUgH8CvRJ5LzAOu5t0k8eyaQKlXbO1BrLxNGLdf/KZ3oC7T7o2Q1zwpd7Kq05VvUTqOOdv/O8IEeVDiPrFZ1hzXh8Le8eQWktb5AMV6DaCbSZduw2APUucdquEzmIk9d6PtFX6tx1bynQGauKyjTNcj9pNSE8KcR8CvqaK0bUsazNk3aAFxcXqQ0j4KTU612fhBndL7sjfMIRiNAcEW7NPrEggC2iBSaxiS7fbkK2RYDFaN7trK5n8SxOLzwOe3MGh0AVueVLKbEK3DaAYfySbApgGZxLmmH4BqxguVIswAybKooeLjFJ+IIj2RTLFcDY7LY7nj77aW2/v2N2A/xO4i+lps+qp1zygLXAk/wlyHeZz/dHv+KbkoK1b8uISl+7MF5OveLwuTNW3lARCkBiU1UTujnKFio31XNgmz828PfhkktT2Id8ksyyZ/GFeUYACU7xI12WgIDjB241kubceb30=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
