travis:
  secure:
    BINSTAR_TOKEN: NoyYJah29ZYi9yh+HbxomuiEdztr7h5bDPNbfarC9J5BOGs7FXvHhXmDiekfHBJq1guILjokFYRsed57CtvOfNaDVHT9Mt80OTzHzFBN/Cx1uXxs4cOzSEr8YwJ/pKGSvIYn/gJ4dbwFEVKZrA/CBcqjuz9LO5xNH9K8u26BnX9wuNlAjcQ/8oFs7Ju0enOSLFL17XSsRR6x7wCR5oMRVie3RiPf1r1Ae/kVWLYdQtqoblyrvVkWTsAluogEHiAhiMVdaOknZzZxj0Fmk8ikjK2iXRpjBadU3dq53NVuvxPoo4g3h4RA+Ut3FLBiGQIF96vDBVWpj0ApTSTdtp6nSrvQWBpTpOBO+ct5Qrubc/BXmV0GgNe21kKXsjfzWkklDNf3e/eLSYPezr/dp+Uk5QWh1Mv1HLcq+3ThWbac1g5NIoL2df8CGm/bpaJtobkc0xUORiA07GOewDdN2Vyaw1k+6iZ8/dCbF+QyO/9mI2EOj9YS4V6ZNvYPI8DShM+8SIn1ACcQ5pToH+20uVQwXCLxYG2IGDAz9vWTdjeG7SKtA/o123k5U4PFvZsufO44zLrgq2sn9xUYAOQzREHmGfvVY/VKg2AMPrUMSJMrsoWQ7bNsXGsuKvMzQ/LVNa3A/uJfvB0q9x6Fhv8pkPL9LYK+DdT5prt2KvM1iEnF3Is=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
